name: Release MacOS ARM64

# Reusable workflow, to be called by release.yml
on:
  workflow_call:
  push:
    tags:
      - "v*.*"
# on:
#   workflow_run:
#     workflows: ['Release']
#     types:
#       - completed

jobs:
  macos:
    name: DMG release
    runs-on: macos-15

    env:
      CC: clang
      CXX: clang++
      
    steps:
      - uses: actions/checkout@v4

      - name: Set environment
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Install
        run: |
          brew install m4 git bison wget autoconf automake
          brew remove llvm@18
          
      - name: Symlink GCC & Fortran
        run: ./etc/actions/macos/link_fortran.sh "$(uname -p)"

      - name: Version
        id: version
        run: |
          VERSION=$(grep AC_INIT configure.ac | cut -d"," -f2 | cut -d"[" -f2 | cut -d"]" -f1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "prefix=/Applications/FreeFem++.app/Contents/ff-$VERSION" >> $GITHUB_OUTPUT
          echo "dmg_dir=FreeFEM-$VERSION-arm" >> $GITHUB_OUTPUT

      - name: Prepare
        run: |
          PREFIX=${{ steps.version.outputs.prefix }}

          sudo mkdir -p "$PREFIX/gnu"
          sudo ./etc/actions/release/macos/copy_fortran.sh "$PREFIX"

      - name: Dependencies
        run: |
          PREFIX=${{ steps.version.outputs.prefix }}

          sudo ./etc/actions/release/macos/compile_gsl.sh "$PREFIX" $CC $CXX
          sudo ./etc/actions/release/macos/compile_hdf5.sh "$PREFIX" $CC $CXX

      - name: Configure
        run: |
          PREFIX=${{ steps.version.outputs.prefix }}

          tar zxvf AutoGeneratedFile.tar.gz
          ./configure --enable-optim --enable-generic --enable-download --enable-m64 \
            --prefix="$PREFIX" \
            "CXXFLAGS=-Wno-undefined-var-template" \
            "FLIBS=-L"$PREFIX/gnu" -lgfortran -lquadmath"
          ./3rdparty/getall -a -o PETSc

      - name: PETSc
        run: |
          cd 3rdparty/ff-petsc
          make petsc-slepc SUDO=sudo
          cd -
          ./reconfigure

      - name: Build
        run: make -j 3

      - name: Check
        continue-on-error: true
        run: make check

      - name: Install
        run: |
          PREFIX=${{ steps.version.outputs.prefix }}

          mkdir -p "$HOME/pkg/$PREFIX"
          rsync -a "$PREFIX/." "$HOME/pkg/$PREFIX/."
          make install DESTDIR="$HOME/pkg"

      - name: Fix gfortran lib
        run: |
          PREFIX=${{ steps.version.outputs.prefix }}

          sudo ./etc/actions/release/macos/fix_fortran.sh "$HOME/pkg" "$PREFIX"

      - name: Create DMG
        id: dmg
        run: |
          DMG_DIR=${{ steps.version.outputs.dmg_dir }}
          VERSION=${{ steps.version.outputs.version }}

          ./etc/actions/release/macos/create_dmg.sh "$HOME/pkg" "$DMG_DIR" "$VERSION"

          echo "file=$DMG_DIR.dmg" >>$GITHUB_OUTPUT

      # - name: Version
      #   id: version
      #   run: echo "version=4.15.1" >> $GITHUB_OUTPUT
      
      # - name: Dumb file
      #   id: dmg
      #   run: echo "TEST" >> test.txt
          
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.dmg.outputs.file }}
          name: v${{ steps.version.outputs.version }}-testActions
